### ISSUE TITLE
mqtt-recorder

### ISSUE THREAD

**Issue by HuiTF** [rpdswtk/mqtt_recorder#7]
When I use mqtt-recorder with --mode replay with --qos 1 --file mqtt_2records.csv, the qos level still remain 0.

**Comment by rpdswtk** [comment]
`qos` parameter is only used for subscription. Using the tool in replay mode will read `qos` from the recorded `.csv` file.

**Comment by HuiTF** [comment]
Official (Closed) - Non Sensitive

Noted with Thanks
